use_frameworks!

platform :ios, '8.0'

target 'AvoidAPPCrashDefenseSDK_Example' do
  pod 'AvoidAPPCrashDefenseSDK', :path => '../'

  target 'AvoidAPPCrashDefenseSDK_Tests' do
    inherit! :search_paths

    
  end
end
